- hosts: master 
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
  vars:
     ansible_python_interpreter: {PATH_TO_PYTHON_EXE}
     install_spark: true
     config_spark: true
  roles:
    - spark
