---
- debug:
    msg: "User is {{ user }} and group is {{ group }}"
- name: Create Spark Path
  vars:
      ansible_python_interpreter: {PATH_TO_PYTHON_EXE}
  file: 
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ spark_create_path }}"
  

- include: install_spark.yml
  when: install_spark

- include: config_spark.yml
  when: config_spark

#- include: redhat.yml
#  when: ansible_os_family == 'RedHat'
